In [1]:
import numpy as np

In [7]:
np.arange(0, 27, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [19]:
np.linspace(0, 7, 27)

array([0.        , 0.26923077, 0.53846154, 0.80769231, 1.07692308,
       1.34615385, 1.61538462, 1.88461538, 2.15384615, 2.42307692,
       2.69230769, 2.96153846, 3.23076923, 3.5       , 3.76923077,
       4.03846154, 4.30769231, 4.57692308, 4.84615385, 5.11538462,
       5.38461538, 5.65384615, 5.92307692, 6.19230769, 6.46153846,
       6.73076923, 7.        ])

In [33]:
arr = np.arange(30)
arr.reshape(6, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [40]:
np.random.rand(3, 2, 4)

array([[[0.20595542, 0.45916076, 0.98014576, 0.93341041],
        [0.71889801, 0.14073852, 0.20416236, 0.83251829]],

       [[0.5530682 , 0.35062228, 0.67992659, 0.83737787],
        [0.84226819, 0.1467731 , 0.09802075, 0.57608803]],

       [[0.34091173, 0.02320373, 0.60523512, 0.8536423 ],
        [0.67825323, 0.20304804, 0.08244283, 0.0327861 ]]])

In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[8, 7], [6, 5]])
np.dot(a, b)

array([[20, 17],
       [48, 41]])

In [42]:
arr = np.array([2, 4, 6, 8, 10])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

6.0
6.0
2.8284271247461903


In [43]:
import pandas as pd